apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  password: password

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  ports:
    - port: 3306
  selector:
    name: mysql
  type: ClusterIP

---

apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
    ports:
    - name: mysql
      containerPort: 3306
      protocol: TCP
    volumeMounts:
    - name: mysql
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql
    emptyDir: {}